In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import seaborn as sns
import matplotlib.pyplot as plt
import scipy as stats

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/student-course-completion-prediction-dataset/Course_Completion_Prediction.csv

# DATA PREPROCESSING #

In [2]:
## importing the dataset

df = pd.read_csv("/kaggle/input/student-course-completion-prediction-dataset/Course_Completion_Prediction.csv")

df.head(3)

,Student_ID,Name,Gender,Age,Education_Level,Employment_Status,City,Device_Type,Internet_Connection_Quality,Course_ID,...,Enrollment_Date,Payment_Mode,Fee_Paid,Discount_Used,Payment_Amount,App_Usage_Percentage,Reminder_Emails_Clicked,Support_Tickets_Raised,Satisfaction_Rating,Completed
0,STU100000,Vihaan Patel,Male,19,Diploma,Student,Indore,Laptop,Medium,C102,...,01-06-2024,Scholarship,No,No,1740,49,3,4,3.5,Completed
1,STU100001,Arjun Nair,Female,17,Bachelor,Student,Delhi,Laptop,Low,C106,...,27-04-2025,Credit Card,Yes,No,6147,86,0,0,4.5,Not Completed
2,STU100002,Aditya Bhardwaj,Female,34,Master,Student,Chennai,Mobile,Medium,C101,...,20-01-2024,NetBanking,Yes,No,4280,85,1,0,5.0,Completed

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 40 columns):
 #   Column                        Non-Null Count   Dtype
---  ------                        --------------   -----
 0   Student_ID                    100000 non-null  object
 1   Name                          100000 non-null  object
 2   Gender                        100000 non-null  object
 3   Age                           100000 non-null  int64
 4   Education_Level               100000 non-null  object
 5   Employment_Status             100000 non-null  object
 6   City                          100000 non-null  object
 7   Device_Type                   100000 non-null  object
 8   Internet_Connection_Quality   100000 non-null  object
 9   Course_ID                     100000 non-null  object
 10  Course_Name                   100000 non-null  object
 11  Category                      100000 non-null  object
 12  Course_Level                  100000 non-null  object
 13  Course_Duration_Days          100000 non-null  int64
 14  Instructor_Rating             100000 non-null  float64
 15  Login_Frequency               100000 non-null  int64
 16  Average_Session_Duration_Min  100000 non-null  int64
 17  Video_Completion_Rate         100000 non-null  float64
 18  Discussion_Participation      100000 non-null  int64
 19  Time_Spent_Hours              100000 non-null  float64
 20  Days_Since_Last_Login         100000 non-null  int64
 21  Notifications_Checked         100000 non-null  int64
 22  Peer_Interaction_Score        100000 non-null  float64
 23  Assignments_Submitted         100000 non-null  int64
 24  Assignments_Missed            100000 non-null  int64
 25  Quiz_Attempts                 100000 non-null  int64
 26  Quiz_Score_Avg                100000 non-null  float64
 27  Project_Grade                 100000 non-null  float64
 28  Progress_Percentage           100000 non-null  float64
 29  Rewatch_Count                 100000 non-null  int64
 30  Enrollment_Date               100000 non-null  object
 31  Payment_Mode                  100000 non-null  object
 32  Fee_Paid                      100000 non-null  object
 33  Discount_Used                 100000 non-null  object
 34  Payment_Amount                100000 non-null  int64
 35  App_Usage_Percentage          100000 non-null  int64
 36  Reminder_Emails_Clicked       100000 non-null  int64
 37  Support_Tickets_Raised        100000 non-null  int64
 38  Satisfaction_Rating           100000 non-null  float64
 39  Completed                     100000 non-null  object
dtypes: float64(8), int64(15), object(17)
memory usage: 30.5+ MB

In [4]:
## Filtering only a specific Python course

df = df[df["Course_Name"].str.contains("Data Analysis with Python", case=False, na=False)]

In [5]:
## Selecting the correct columns

req_columns = ["Student_ID",
           "Gender",
           "Age",
           "Education_Level",
           "Employment_Status",
           "Device_Type",
           "Login_Frequency",
           "Average_Session_Duration_Min",
           "Video_Completion_Rate",
           "Discussion_Participation",
           "Time_Spent_Hours",
           "Peer_Interaction_Score",
           "Assignments_Submitted",
           "Assignments_Missed",
            "Notifications_Checked",
            "Reminder_Emails_Clicked",
           "Progress_Percentage",
          "Rewatch_Count",
          "Completed"]

df = df[req_columns]

df.head(3)

,Student_ID,Gender,Age,Education_Level,Employment_Status,Device_Type,Login_Frequency,Average_Session_Duration_Min,Video_Completion_Rate,Discussion_Participation,Time_Spent_Hours,Peer_Interaction_Score,Assignments_Submitted,Assignments_Missed,Notifications_Checked,Reminder_Emails_Clicked,Progress_Percentage,Rewatch_Count,Completed
0,STU100000,Male,19,Diploma,Student,Laptop,3,30,55.0,2,0.5,4.3,8,1,6,3,70.8,0,Completed
5,STU100005,Female,21,Bachelor,Student,Mobile,7,30,85.9,1,11.8,6.2,7,3,9,5,75.3,5,Completed
14,STU100014,Male,19,Diploma,Employed,Mobile,5,23,73.8,3,0.5,10.0,2,8,4,1,40.9,3,Not Completed

In [6]:
len(df)

15465